version: '2'

services:

# LAVA server (for testing) instance inheriting from ci-box-lava-master
  lava-server:
    container_name: lava-server
    hostname: lava-server
    extends:
      file: ./ci-box-lava-master/docker-compose.yml
      service: lava-server
    build:
      args:
        admin_username: admin
        admin_password: password
        admin_token: "d0siRzClNHWNtUYJbpmjOPEyPp0QLCKqQtDGTftN"
        workers: lava_worker0
    networks:
      default:
        aliases:
          - lava.server
    ports:
      - "8080:80" # expose http to outside
    volumes:
      - ./overlays/lava-server/etc/lava-server/dispatcher-config/devices:/etc/lava-server/dispatcher-config/devices
      - ./overlays/lava-server/etc/lava-server/dispatcher-config/health-checks:/etc/lava-server/dispatcher-config/health-checks

# LAVA worker0 (for testing) instance inheriting from ci-box-lava-worker
  lava-worker0:
    container_name: lava_worker0
    hostname: lava_worker0
    extends:
      file: ./ci-box-lava-worker/docker-compose.yml
      service: lava-worker
    build:
      args:
        server: lava-server
        extra_packages: "microcom"
    volumes:
      # used for fastboot and ftdi
      - /dev:/dev
      # lava-lxc-create mocker with arg fixed
      - ./overlays/lava-worker/usr/bin/lxc-create:/usr/bin/lxc-create
      # To connect USB serial by serial number
      - ./overlays/lava-worker/usr/bin/ftdi-connect:/usr/bin/ftdi-connect
      # libguestfs/supermin
      - /boot:/boot:ro
      - /lib/modules:/lib/modules:ro
    privileged: true
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb

# SQUAD - Software Quality Dashboard
  squad:
    container_name: squad
    hostname: squad
    extends:
      file: ./ci-box-squad/docker-compose.yml
      service: squad
    build:
      args:
        admin_username: admin
        admin_password: password
        admin_token: "2d703e793ea345efdbab52d95fe33ec715bcc2d4"
        group: "Linaro"
        projects: "openembedded-rpb-db410c linux-qcomlt openembedded-x15 android zephyr-master"
        # Lava test execution backend
        lava_server: lava.server
        lava_username: admin
        lava_token: "d0siRzClNHWNtUYJbpmjOPEyPp0QLCKqQtDGTftN"
    ports: # expose http to outside
      - "8081:80"

# File Server (FTP/HTTP) to store artifacts (images, test templates...)
  fileserver:
    container_name: fileserver
    hostname: fileserver
    extends:
      file: ./ci-box-fileserver/docker-compose.yml
      service: fileserver
    build:
      args:
        http_port: 80
        ftp_port: 21
        root: "/wwwroot"
    ports: # expose http to outside
      - "8082:80"
    volumes:
      - ./overlays/fileserver/wwwroot:/wwwroot

# Jenkins (for building) instance inheriting from ci-box-jenkins
  jenkins:
    container_name: jenkins
    hostname: jenkins
    extends:
      file: ./ci-box-jenkins/docker-compose.yml
      service: jenkins
    build:
      args:
        admin_username: admin
        admin_password: password
        http_port: 8080
        extra_packages: "build-essential gcc-aarch64-linux-gnu bc lava-tool ftp gettext-base"
        plugins: "git mailer git-parameter build-timeout publish-over-ftp"
    ports:
      - "8085:8080"
    volumes:
      - ./overlays/jenkins/var/jenkins_home/jobs:/var/jenkins_home/jobs
